import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { createD1Repository } from '../src/db/d1-repository';
import { parseSearchParams } from '../src/domain/search';

class Stmt { values: unknown[]=[]; constructor(private db: DatabaseSync, readonly sql:string){} bind(...v:unknown[]){this.values=v;return this;} async all<T>(){return {results:this.db.prepare(this.sql).all(...(this.values as any[])) as T[]};} async run(){const r=this.db.prepare(this.sql).run(...(this.values as any[]));return {meta:{changes:Number(r.changes)}};} }
class D1 { statements:Stmt[]=[]; constructor(readonly db:DatabaseSync){} prepare(sql:string){const s=new Stmt(this.db,sql);this.statements.push(s);return s;} async batch(ss:Stmt[]){this.db.exec('BEGIN');try{const r=[];for(const s of ss)r.push(await s.run());this.db.exec('COMMIT');return r;}catch(e){this.db.exec('ROLLBACK');throw e;}} }
function fixture(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(resolve(process.cwd(),'migrations/0001_initial.sql'),'utf8'));db.exec(`INSERT INTO market_sources(id,name,api_key_hash,created_at,updated_at) VALUES('s','Synthetic','hash',0,0); INSERT INTO shops(id,source_id,identity_hash,public_shop_id,vendor_account_id,vendor_name,vendor_name_normalized,title,title_normalized,shop_type,map_name,x,y,status,profile_hash,last_status_observed_at,last_changed_at) VALUES (1,'s','i1','p1','v1','普通商人','普通商人','利卡特价','利卡特价','sell','prontera',1,1,'active','p',0,0),(2,'s','i2','p2','v2','杰利卡','杰利卡','普通商店','普通商店','sell','prontera',1,1,'active','p',0,0),(3,'s','i3','p3','v3','普通商人','普通商人','普通商店','普通商店','sell','prontera',1,1,'active','p',0,0); INSERT INTO listings(id,shop_id,item_fingerprint,item_id,price,quantity,status,first_seen_at,last_changed_at,last_changed_snapshot_id) VALUES (1,1,'f1',100,10,1,'active',0,0,'b'),(2,2,'f2',101,20,1,'active',0,0,'b'),(3,3,'f3',4001,30,1,'active',0,0,'b');`);return {db, d1:new D1(db)};}
async function search(repo:any,q:string){return repo.searchListings(parseSearchParams(new URL('https://x.test/api/v1/market/search?'+q),{verifyCursor:false}));}
describe('clean-break D1 search',()=>{
it('ORs catalog item ids with shop title and vendor substring matches',async()=>{const {db,d1}=fixture();const repo=createD1Repository(d1 as never);const page=await search(repo,'item_ids=4001&q=利卡');expect(page.items.map((x:any)=>x.id)).toEqual([1,2,3]);const statement=d1.statements.find(s=>s.sql.includes('FROM listings l'))!;expect(statement.sql).toMatch(/l\.item_id IN .*OR.*s\.title_normalized LIKE/s);expect(statement.sql).toMatch(/vendor_name_normalized.*LIKE/s);expect(statement.sql).not.toMatch(/fts|search_short_tokens|item_catalog/i);db.close();});
it('supports item-only, shop-only, and vendor-only searches',async()=>{const {db,d1}=fixture();const repo=createD1Repository(d1 as never);expect((await search(repo,'item_ids=4001')).items.map((x:any)=>x.id)).toEqual([3]);expect((await search(repo,'q=利卡')).items.map((x:any)=>x.id)).toEqual([1,2]);expect((await search(repo,'q=杰利')).items.map((x:any)=>x.id)).toEqual([2]);db.close();});
it('does not run shop/vendor search for one character',async()=>{const {db,d1}=fixture();const repo=createD1Repository(d1 as never);const page=await search(repo,'q=利');expect(page.items).toHaveLength(3);const statement=d1.statements.find(s=>s.sql.includes('FROM listings l'))!;expect(statement.sql).not.toContain('LIKE');db.close();});
	it('enforces limit and item_ids',async()=>{const {db,d1}=fixture();const repo=createD1Repository(d1 as never);const page=await search(repo,'item_ids=100&limit=500');expect(page.items.map((x:any)=>x.itemId)).toEqual([100]);const statement=d1.statements.find(s=>s.sql.includes('FROM listings l'))!;expect(statement.values).toContain(51);db.close();});
	it('returns each listing shop coordinates',async()=>{const {db,d1}=fixture();const repo=createD1Repository(d1 as never);const page=await search(repo,'item_ids=100');expect(page.items.map((item:any)=>({x:item.x,y:item.y}))).toEqual([{x:1,y:1}]);db.close();});
});
