CREATE TABLE IF NOT EXISTS market_sources (
  id VARCHAR(191) NOT NULL,
  name VARCHAR(255) NOT NULL,
  api_key_hash CHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  last_upload_at BIGINT UNSIGNED NULL,
  last_full_snapshot_id VARCHAR(191) NULL,
  last_full_snapshot_at BIGINT UNSIGNED NULL,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_market_sources_api_key_hash (api_key_hash),
  CONSTRAINT chk_market_sources_status CHECK (status IN ('active', 'disabled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS shops (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_id VARCHAR(191) NOT NULL,
  identity_hash CHAR(64) NOT NULL,
  public_shop_id VARCHAR(191) NOT NULL,
  vendor_account_id VARCHAR(191) NOT NULL,
  vendor_name VARCHAR(191) NOT NULL DEFAULT '',
  vendor_name_normalized VARCHAR(128) NOT NULL DEFAULT '',
  title VARCHAR(191) NOT NULL DEFAULT '',
  title_normalized VARCHAR(128) NOT NULL DEFAULT '',
  shop_type VARCHAR(4) NOT NULL,
  map_name VARCHAR(64) NOT NULL DEFAULT '',
  x INT UNSIGNED NOT NULL DEFAULT 0,
  y INT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  profile_hash CHAR(64) NOT NULL,
  full_state_hash CHAR(64) NULL,
  state_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
  missing_full_count INT UNSIGNED NOT NULL DEFAULT 0,
  last_missing_snapshot_id VARCHAR(191) NULL,
  last_status_observed_at BIGINT UNSIGNED NOT NULL,
  last_changed_at BIGINT UNSIGNED NOT NULL,
  closed_at BIGINT UNSIGNED NULL,
  close_reason VARCHAR(32) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_shops_source_identity (source_id, identity_hash),
  UNIQUE KEY uq_shops_source_public_id (source_id, public_shop_id),
  INDEX idx_shops_active_directory (status, title_normalized, vendor_name_normalized, map_name, shop_type, id),
  INDEX idx_shops_active_filter (status, map_name, shop_type, id),
  INDEX idx_shops_source_lifecycle (source_id, status, missing_full_count, id),
  CONSTRAINT fk_shops_source FOREIGN KEY (source_id) REFERENCES market_sources (id) ON DELETE CASCADE,
  CONSTRAINT chk_shops_type CHECK (shop_type IN ('buy', 'sell')),
  CONSTRAINT chk_shops_status CHECK (status IN ('active', 'stale', 'closed')),
  CONSTRAINT chk_shops_x CHECK (x >= 0),
  CONSTRAINT chk_shops_y CHECK (y >= 0),
  CONSTRAINT chk_shops_state_version CHECK (state_version >= 0),
  CONSTRAINT chk_shops_missing_full_count CHECK (missing_full_count >= 0),
  CONSTRAINT chk_shops_close_reason CHECK (close_reason IS NULL OR close_reason IN ('explicit_dismissed', 'missing_full'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS listings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  shop_id BIGINT UNSIGNED NOT NULL,
  item_fingerprint CHAR(64) NOT NULL,
  item_key VARCHAR(191) NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  upgrade INT UNSIGNED NOT NULL DEFAULT 0,
  slots INT UNSIGNED NOT NULL DEFAULT 0,
  card0 BIGINT UNSIGNED NOT NULL DEFAULT 0,
  card1 BIGINT UNSIGNED NOT NULL DEFAULT 0,
  card2 BIGINT UNSIGNED NOT NULL DEFAULT 0,
  card3 BIGINT UNSIGNED NOT NULL DEFAULT 0,
  price BIGINT UNSIGNED NOT NULL,
  quantity BIGINT UNSIGNED NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  state_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
  missing_full_count INT UNSIGNED NOT NULL DEFAULT 0,
  last_missing_snapshot_id VARCHAR(191) NULL,
  first_seen_at BIGINT UNSIGNED NOT NULL,
  last_changed_at BIGINT UNSIGNED NOT NULL,
  last_changed_snapshot_id VARCHAR(191) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_listings_shop_fingerprint (shop_id, item_fingerprint),
  INDEX idx_listings_active_item_price (status, item_id, price, id),
  INDEX idx_listings_active_shop_price (status, shop_id, price, id),
  INDEX idx_listings_active_price (status, price, id),
  INDEX idx_listings_shop_status (shop_id, status, id),
  CONSTRAINT fk_listings_shop FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE CASCADE,
  CONSTRAINT chk_listings_item_id CHECK (item_id >= 0),
  CONSTRAINT chk_listings_upgrade CHECK (upgrade >= 0),
  CONSTRAINT chk_listings_slots CHECK (slots >= 0),
  CONSTRAINT chk_listings_price CHECK (price >= 0),
  CONSTRAINT chk_listings_quantity CHECK (quantity >= 0),
  CONSTRAINT chk_listings_status CHECK (status IN ('active', 'missing', 'sold_out', 'expired')),
  CONSTRAINT chk_listings_state_version CHECK (state_version >= 0),
  CONSTRAINT chk_listings_missing_full_count CHECK (missing_full_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS listing_options (
  listing_id BIGINT UNSIGNED NOT NULL,
  option_index INT UNSIGNED NOT NULL,
  option_type BIGINT UNSIGNED NOT NULL,
  option_value BIGINT NOT NULL,
  option_param BIGINT NOT NULL,
  PRIMARY KEY (listing_id, option_index),
  INDEX idx_listing_options_lookup (option_type, option_value, option_param, listing_id),
  CONSTRAINT fk_listing_options_listing FOREIGN KEY (listing_id) REFERENCES listings (id) ON DELETE CASCADE,
  CONSTRAINT chk_listing_options_index CHECK (option_index >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS listing_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  listing_id BIGINT UNSIGNED NOT NULL,
  snapshot_id VARCHAR(191) NOT NULL,
  observed_at BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  from_price BIGINT UNSIGNED NULL,
  to_price BIGINT UNSIGNED NOT NULL,
  from_quantity BIGINT UNSIGNED NULL,
  to_quantity BIGINT UNSIGNED NOT NULL,
  sold_quantity BIGINT UNSIGNED NOT NULL DEFAULT 0,
  reason VARCHAR(32) NULL,
  transition_key VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_listing_events_transition_key (transition_key),
  INDEX idx_listing_events_history (listing_id, observed_at DESC, id DESC),
  CONSTRAINT fk_listing_events_listing FOREIGN KEY (listing_id) REFERENCES listings (id) ON DELETE CASCADE,
  CONSTRAINT chk_listing_events_type CHECK (event_type IN ('first_seen', 'state_changed', 'missing', 'reappeared', 'expired')),
  CONSTRAINT chk_listing_events_to_price CHECK (to_price >= 0),
  CONSTRAINT chk_listing_events_to_quantity CHECK (to_quantity >= 0),
  CONSTRAINT chk_listing_events_sold_quantity CHECK (sold_quantity >= 0),
  CONSTRAINT chk_listing_events_reason CHECK (reason IS NULL OR reason IN ('price', 'quantity_decrease', 'sold_out', 'missing_full', 'reappeared', 'shop_closed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS upload_batches (
  source_id VARCHAR(191) NOT NULL,
  batch_id VARCHAR(191) NOT NULL,
  snapshot_id VARCHAR(191) NOT NULL,
  part_index INT UNSIGNED NOT NULL,
  part_count INT UNSIGNED NOT NULL,
  snapshot_mode VARCHAR(16) NOT NULL,
  payload_hash CHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL,
  shop_ids_json MEDIUMTEXT NOT NULL,
  response_json MEDIUMTEXT NULL,
  received_at BIGINT UNSIGNED NOT NULL,
  completed_at BIGINT UNSIGNED NULL,
  PRIMARY KEY (source_id, batch_id),
  UNIQUE KEY uq_upload_batches_snapshot_part (source_id, snapshot_id, part_index),
  INDEX idx_upload_batches_snapshot (source_id, snapshot_id, status, part_index),
  CONSTRAINT fk_upload_batches_source FOREIGN KEY (source_id) REFERENCES market_sources (id) ON DELETE CASCADE,
  CONSTRAINT chk_upload_batches_part_index CHECK (part_index BETWEEN 0 AND 15),
  CONSTRAINT chk_upload_batches_part_count CHECK (part_count BETWEEN 1 AND 16),
  CONSTRAINT chk_upload_batches_mode CHECK (snapshot_mode IN ('full', 'delta', 'heartbeat')),
  CONSTRAINT chk_upload_batches_status CHECK (status IN ('processing', 'accepted', 'rejected')),
  CONSTRAINT chk_upload_batches_shop_ids_json CHECK (JSON_VALID(shop_ids_json))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
