import { createHash, randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

function optionValue(name, fallback) {
  const index = process.argv.indexOf(name);
  return index === -1 ? fallback : process.argv[index + 1];
}

const outputDir = resolve(optionValue('--output-dir', process.cwd()));
const force = process.argv.includes('--force');
const localPath = resolve(outputDir, '.dev.vars');
const deploymentPath = resolve(outputDir, '.deployment-secrets.local');

for (const path of [localPath, deploymentPath]) {
  if (!force && existsSync(path)) {
    console.error(`${path} already exists; use --force only when rotating every generated credential.`);
    process.exit(1);
  }
}

const secret = () => randomBytes(32).toString('base64url');
const hash = (value) => createHash('sha256').update(value).digest('hex');
const localSourceKey = secret();
const stagingSourceKey = secret();
const productionSourceKey = secret();

const local = [
  '# Generated by pnpm secrets:generate. Do not commit this file.',
  'ENVIRONMENT=local',
  'BUILD_VERSION=dev',
  'MAX_BODY_BYTES=524288',
  '# Point local development at a MySQL 8 server. Replace before running Wrangler.',
  'MYSQL_URL=mysql://replace-user:replace-password@replace-host:3306/replace-database?ssl=true',
  '# Optional integration-test target; never point this at production.',
  'MYSQL_TEST_URL=mysql://replace-user:replace-password@replace-host:3306/replace-test-database?ssl=true',
  'ALLOW_MYSQL_TEST_DESTRUCTIVE=0',
  `UPLOAD_API_KEY=${localSourceKey}`,
  `UPLOAD_API_KEY_SHA256=${hash(localSourceKey)}`,
  `ADMIN_SECRET=${secret()}`,
  `CURSOR_SECRET=${secret()}`,
  '',
].join('\n');

const deployment = [
  '# Generated deployment credentials. Do not commit, paste into logs, or send in chat.',
  '# The source API key is given to the uploader; only its SHA-256 hash is stored in MySQL.',
  `STAGING_SOURCE_API_KEY=${stagingSourceKey}`,
  `STAGING_SOURCE_API_KEY_SHA256=${hash(stagingSourceKey)}`,
  `STAGING_CURSOR_SECRET=${secret()}`,
  `STAGING_ADMIN_SECRET=${secret()}`,
  `PRODUCTION_SOURCE_API_KEY=${productionSourceKey}`,
  `PRODUCTION_SOURCE_API_KEY_SHA256=${hash(productionSourceKey)}`,
  `PRODUCTION_CURSOR_SECRET=${secret()}`,
  `PRODUCTION_ADMIN_SECRET=${secret()}`,
  '',
].join('\n');

mkdirSync(outputDir, { recursive: true });
writeFileSync(localPath, local, { encoding: 'utf8', mode: 0o600 });
writeFileSync(deploymentPath, deployment, { encoding: 'utf8', mode: 0o600 });
console.log(`Generated ${localPath} and ${deploymentPath}. Secret values were not printed.`);
